export const DEFAULT_CAT_BREED = {
    weight: { imperial: "10-15", metric: "4-7" },
    id: "abys",
    name: "Abyssinian",
    cfa_url: "http://cfa.org/Breeds/BreedsAB/AmericanBobtail.aspx",
    vetstreet_url: "http://www.vetstreet.com/cats/american-bobtail",
    vcahospitals_url:
        "https://vcahospitals.com/know-your-pet/cat-breeds/american-bobtail",
    temperament: "Intelligent, Interactive, Lively, Playful, Sensitive",
    origin: "Egypt",
    country_codes: "Egt",
    country_code: "Egt",
    description:
        "Abyssinian  are loving and incredibly intelligent cats possessing a distinctive wild appearance. They are extremely interactive cats that bond with their human family with great devotion.",
    life_span: "11 - 15",
    indoor: 1,
    lap: 1,
    alt_names: "ABT, Bobtail",
    adaptability: 2,
    affection_level: 5,
    child_friendly: 3,
    dog_friendly: 5,
    energy_level: 3,
    grooming: 1,
    health_issues: 2,
    intelligence: 5,
    shedding_level: 3,
    social_needs: 4,
    stranger_friendly: 3,
    vocalisation: 3,
    experimental: 1,
    hairless: 1,
    natural: 1,
    rare: 1,
    rex: 1,
    suppressed_tail: 1,
    short_legs: 1,
    wikipedia_url: "https://en.wikipedia.org/wiki/American_Bobtail",
    hypoallergenic: 1,
    reference_image_id: "hMyT4CDXR",
    image: {
        id: "hMyT4CDXR",
        width: 1600,
        height: 1200,
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7bj6E8JjqMi2shpN34XabPSYmhz_oGvs-37YeTUzvlQ&s",
    },
};
