export const DEFAULT_CAT_BREED = {
    weight: { imperial: "10-15", metric: "4-7" },
    id: "abys",
    name: "Abyssinian",
    cfa_url: "http://cfa.org/Breeds/BreedsAB/AmericanBobtail.aspx",
    vetstreet_url: "http://www.vetstreet.com/cats/american-bobtail",
    vcahospitals_url:
        "https://vcahospitals.com/know-your-pet/cat-breeds/american-bobtail",
    temperament: "Intelligent, Interactive, Lively, Playful, Sensitive",
    origin: "Egypt",
    country_codes: "Egt",
    country_code: "Egt",
    description:
        "The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.",
    life_span: "11 - 15",
    indoor: 1,
    lap: 1,
    alt_names: "ABT, Bobtail",
    adaptability: 5,
    affection_level: 5,
    child_friendly: 3,
    dog_friendly: 4,
    energy_level: 5,
    grooming: 1,
    health_issues: 2,
    intelligence: 5,
    shedding_level: 3,
    social_needs: 5,
    stranger_friendly: 3,
    vocalisation: 3,
    experimental: 1,
    hairless: 1,
    natural: 1,
    rare: 1,
    rex: 1,
    suppressed_tail: 1,
    short_legs: 1,
    wikipedia_url: "https://en.wikipedia.org/wiki/Abyssinian_cat",
    hypoallergenic: 1,
    reference_image_id: "hMyT4CDXR",
    image: {
        id: "hMyT4CDXR",
        width: 1600,
        height: 1200,
        url: "https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg",
    },
};
